### ISSUE TITLE
Wrong image format

### ISSUE THREAD

**Issue by FilipVaverka** [GabMus/ocl_watershed#1]
It seems the issue is you are using wrong combination of image format and read/write_imageX in the kernel
CL_UNORM_INT8 should be R/W with write_imagef or you would want to use CL_UNSIGNED_INT8 with *_imageui
https://stackoverflow.com/questions/31718492/meaning-of-cl-unorm-int8-for-cl-image-format-image-channel-data-type-and-its-di (and yea, it took me a while to find out about this...)

(in case IRC message gets lost somewhere)

**Comment by GabMus** [comment]
perfect, that works now. thank you so much!
